package getl

// Table is a representation of a table of data.
type Table interface {
	// Scan advances the Table to the next Row, which will be available through the Row method. It
	// returns false when the scan stops, either by reaching the end of the input or an error. After
	// Scan returns false, the Err method will return any error that occurred during scanning,
	// except that if it was io.EOF, Err will return nil.
	Scan() bool
	// Row returns the most recent Row generated by a call to Scan.
	Row() Row
	// Err returns the first non-EOF error that was encountered by the Table.
	Err() error
}

// Row is a representation of a line of data in a Table.
type Row map[string]interface{}
